name: Build Artifacts
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make COSMO=amalgamation-tiny

      #- name: tests
      #run: |
      #    echo 0 | sudo tee /proc/sys/fs/binfmt_misc/status
      #    make test
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        # Artifact name
        name: cosmosocks
        # A file, directory or wildcard pattern that describes what to upload
        path: |
            cosmosocks_server
            cosmosocks_server_ape
        if-no-files-found: error
  linux:
    runs-on: ${{ matrix.os }}
    strategy:
        fail-fast: false
        matrix:
            os: [ubuntu-latest]
    needs: build
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
    - name: tests
      run: |
          echo 0 | sudo tee /proc/sys/fs/binfmt_misc/status
          chmod +x cosmosocks/*
          cp cosmosocks/* .
          make test
  macos:
    runs-on: ${{ matrix.os }}
    strategy:
        fail-fast: false
        matrix:
            os: [macOS-latest]
    needs: build
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
    - name: Setup upterm session
      uses: lhotari/action-upterm@v1
      with:
        ## limits ssh access and adds the ssh public key for the user which triggered the workflow
		limit-access-to-actor: true
        ## limits ssh access and adds the ssh public keys of the listed GitHub users
        limit-access-to-users: bannsec

    - name: tests
      run: |
          chmod +x cosmosocks/*
          cp cosmosocks/* .
          NONINTERACTIVE=1 brew install coreutils
          make test
