name: Build Artifacts
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make COSMO=amalgamation-tiny

      #- name: tests
      #run: |
      #    echo 0 | sudo tee /proc/sys/fs/binfmt_misc/status
      #    make test
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        # Artifact name
        name: cosmosocks
        # A file, directory or wildcard pattern that describes what to upload
        path: |
            cosmosocks_server
            cosmosocks_server_ape
        if-no-files-found: error
  tests-linux:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
    - name: tests
      run: |
          echo 0 | sudo tee /proc/sys/fs/binfmt_misc/status
          chmod +x ${{steps.download.outputs.download-path}}/*
          cp ${{steps.download.outputs.download-path}}/* .
          make test
